en/docs/release-notes/version-3.3.0.md

Add the 3.3.0 release note

---

en/docs/release-notes/version-3.3.0.md

Add the 3.3.0 release note images

Add the 3.3.0 release note images

---

README.md

Add a space

---

en/docs/release-notes/version-3.3.0.md

Update the image paths

---

LICENSE
en/docs/release-notes/version-3.3.0.md
en/mkdocs.yml

Add the VS Code extension license

Add the VS Code extension license

---

LICENSE

Revert the doc repo license change

Revert the doc repo license change

---

en/docs/release-notes/version-3.3.0.md

Address more review comments

---

en/docs/edit-the-code/code-navigation.md
en/docs/edit-the-code/diagnostics.md

Fix broken links of navigation/diagnostic images

---

en/docs/release-notes/version-3.3.0.md

Address review comments of the 3.3.0 release note

Address review comments of the 3.3.0 release note

---

README.md

Replace word `plugin` with `extension`

Replace word `plugin` with `extension`

---

en/docs/architecture-diagram/architecture-diagram.md
en/docs/build-and-run/build-and-run.md
en/docs/build-and-run/build-jar.md
en/docs/build-and-run/tryit-tools/graphql-tool.md
en/docs/build-and-run/tryit-tools/swagger-tool.md
en/docs/debugging/debug.md
en/docs/get-started/install.md
en/docs/get-started/open-packages.md
en/docs/index.md
en/docs/references/how-to-use-statement-editor.md
en/mkdocs.yml

Improve VS Code docs

---

en/docs/debug.md
en/docs/edit-the-code/code-actions.md

Review `Code actions` and `Debug` pages

Review `Code actions` and `Debug` pages

---

en/docs/visual-programming/data-mapper.md

Review the `Data mapper` page

---

en/docs/index.md

These are the links added to card in the landing page:
- Run and try: https://wso2.com/ballerina/vscode/docs/build-and-run/build-and-run/
- Visual programming: https://wso2.com/ballerina/vscode/docs/visual-programming/sequence-diagram-view/ 
- Coding: http://localhost:8000/edit-the-code/intellisense/
- Debug: https://wso2.com/ballerina/vscode/docs/debug/'

Replace landing page

---

en/docs/visual-programming/project-design-view.md

Image size consistency will be verified separately.

Fix workspace image

---

en/mkdocs.yml

Change release notes in left nav

Change release notes in left nav

---

en/theme/material/partials/header.html

Update the top banner text

---

en/docs/debug-the-code.md
en/docs/get-started/build-the-executables.md
en/docs/get-started/install-the-extension.md
en/docs/get-started/run-a-program.md
en/docs/get-started/try-the-code/try-graphql-services.md
en/docs/get-started/try-the-code/try-http-services.md
en/docs/references/convert-json-to-records.md
en/docs/references/record-editor.md
en/docs/references/statement-editor/statement-editor-overview.md
en/docs/visual-programming/data-mapper.md
en/docs/visual-programming/project-design-view.md
en/theme/material/assets/stylesheets/choreo-docs-theme.css

Update tip, note, and info boxes formatting

Update tip, note, and info boxes formatting

---

en/docs/get-started/build-the-executables.md

Remove unnecessary sections

---

en/docs/assets/css/theme.css
en/docs/debug-the-code.md

Update the debug page

---

en/docs/debug-the-code.md

Fix minor typo

---

en/docs/assets/css/theme.css
en/docs/configure-the-extension.md
en/docs/visual-programming/data-mapper.md

Comment uncommented search code

Comment uncommented search code

---

README.md
en/theme/material/templates/home-page.html

Update the doc site title

---

en/docs/visual-programming/data-mapper.md

Add leading sentence in prerequisites section

Add leading sentence in prerequisites section

---

en/docs/references/convert-json-to-records.md

Update the `Convert JSON to records` page

Update the `Convert JSON to records` page

---

en/docs/assets/css/theme.css

Uncomment code in `theme.css`

---

en/docs/assets/css/theme.css

Update highlighting colors in Algolia

---

en/docs/get-started/install-the-extension.md

Test image rendering issue

---

en/docs/get-started/install-the-extension.md

Update hosted image path

---

en/docs/debug-the-code.md
en/docs/edit-the-code/diagnostics.md
en/docs/get-started/run-a-program.md
en/docs/get-started/try-the-code/try-graphql-services.md
en/docs/get-started/try-the-code/try-http-services.md
en/docs/notebooks.md
en/docs/references/convert-json-to-records.md
en/docs/references/record-editor.md
en/docs/references/statement-editor/call-a-ballerina-library-function.md
en/docs/references/statement-editor/construct-a-record.md
en/docs/references/statement-editor/define-a-configurable-variable.md
en/docs/references/statement-editor/statement-editor-overview.md
en/docs/visual-programming/data-mapper.md
en/docs/visual-programming/project-design-view.md
en/docs/visual-programming/sequence-diagram-view.md

Update hosted image paths

---

en/docs/debug-the-code.md

Fix the image on the `Debug` page.

Fix the image on the `Debug` page

---

en/docs/notebooks.md

Update Notebooks page intro

---

en/docs/notebooks.md

Fix image path

---

en/theme/material/assets/stylesheets/choreo-docs-theme.css

Fix spacing between titles and content

Fix spacing between titles and content

---

en/theme/material/base.html

Remove the Google indexing blocking

Remove the Google indexing blocking

---

en/mkdocs.yml

Remove the dot in the term `LLC`.

Remove dot in the term `LLC`

---

en/mkdocs.yml

Update the copyright statement year.

Update the copyright statement year

---

en/docs/release-notes/version-3.3.0.md
en/docs/release-notes/version-4.0.0.md
en/mkdocs.yml

Create the 4.0.0 release note

---

en/docs/visual-programming/architecture-view/architecture-diagram.md

Fix image on Architecture View page

Fix image on Architecture View page

---

en/docs/release-notes/version-4.0.0.md
en/docs/visual-programming/architecture-view/type-diagram.md
en/docs/visual-programming/http-api-designer.md

Fix more issues

---

en/docs/visual-programming/sequence-diagram-view.md

Remove related topics in the sequence diagram page

Remove related topics in the sequence diagram page

---

en/docs/configure-the-extension.md

Fix broken links

---

en/docs/get-started/try-the-code/try-http-services.md

Fix image sizes

---

en/theme/material/templates/home-page.html

Enable Google indexing in the VS Code extension docs site

Enable Google indexing in the VS Code extension docs site

---

en/theme/material/base.html
en/theme/material/templates/home-page.html

Enable Google Tag Manager and Cookie Pro.

Enable Google Tag Manager and Cookie Pro

---

en/theme/material/base.html
en/theme/material/templates/home-page.html

Fix new VS Code site build errors.

Fix new VS Code site build errors

---

en/docs/index.md

Fix new VS Code site build error.

Fix new VS Code site build error

---

en/docs/index.md
en/theme/material/base.html
en/theme/material/templates/home-page.html

Remove the `icons.html` references.

Remove the `icons.html` references

---

en/docs/index.md
en/theme/material/base.html
en/theme/material/templates/home-page.html

Reverts wso2/docs-ballerina-vscode-extension#186

Revert "Remove the `icons.html` references"

---

en/docs/index.md

Reverts wso2/docs-ballerina-vscode-extension#185

Revert "Fix new VS Code site build error"

---

en/theme/material/base.html
en/theme/material/templates/home-page.html

Reverts wso2/docs-ballerina-vscode-extension#184

Revert "Fix new VS Code site build errors"

---

en/mkdocs.yml
en/theme/material/base.html

Reverts wso2/docs-ballerina-vscode-extension#192

Revert "Fix header details"

---

en/mkdocs.yml
en/theme/material/base.html

Remove repo details from the header

---

en/mkdocs.yml
en/theme/material/base.html

Reverts wso2/docs-ballerina-vscode-extension#195

Revert "Remove repo details from the header"

---

en/docs/debug-the-code/index.md
en/docs/design-services/index.md
en/docs/design-your-application/index.md
en/docs/develop-the-code/index.md
en/docs/implement-the-code/index.md
en/docs/references/statement-editor/index.md
en/docs/try-the-code/index.md
en/mkdocs.yml

Add overview pages

---

en/mkdocs.yml

Remove statement editor overview from left nav.

Remove statement editor overview from left nav

---

en/docs/test-the-code.md
en/docs/troubleshoot.md

Do final changes of the new and overview pages.

 Do final changes of the new and overview pages

---

en/docs/deploy-with-wso2-choreo.md
en/docs/design-your-project/index.md

Improve the revamped content

---

en/docs/troubleshoot.md

Fix the GIF on the troubleshoot page.

Fix the GIF on the troubleshoot page

---

en/docs/debug-the-code/debugging-configurations.md
en/docs/debug-the-code/debugging-sessions.md
en/docs/design-the-project/explore-the-architecture-view.md
en/docs/index.md
en/docs/run-a-program.md

Fix broken links after restructuring.

Fix broken links after restructuring

---

en/docs/assets/css/choreotheme.css
en/docs/debug-the-code/debug-configurations.md
en/docs/debug-the-code/debug-features.md
en/docs/debug-the-code/debug-sessions.md
en/docs/debug-the-code/index.md
en/docs/design-the-project/explore-the-architecture-view.md
en/docs/references/statement-editor/construct-a-record.md
en/docs/references/statement-editor/define-a-configurable-variable.md
en/docs/test-the-code.md
en/mkdocs.yml

Rename debug pages and do other minor fixes.

Rename debug pages and do other minor fixes

---

en/docs/design-the-services/graphql-service-designer.md
en/docs/design-the-services/index.md
en/mkdocs.yml

Rename the GraphQL designer page.

Rename the GraphQL designer page

---

en/docs/license.md
en/docs/release-notes/version-3.3.0.md
en/docs/release-notes/version-4.0.0.md
en/docs/try-the-services/try-http-services.md

Fix issues post restructuring.

Fix issues post restructuring

---

en/docs/release-notes/version-4.3.0.md

Update the 4.3.0 release note.

Update the 4.3.0 release note

---

en/docs/implement-the-code/sequence-diagram-view.md

Fix the Sequence Diagram View page.

Fix the Sequence Diagram View page

---

en/docs/deploy-with-wso2-choreo.md
en/docs/get-started.md
en/docs/implement-the-code/sequence-diagram-view.md

Fix issues in existing content.

Fix issues in existing content

---

en/mkdocs.yml

Remove home from VS Code left nav.

Remove home from VS Code left nav

---

vs-code-home-page/components/vs-code-home-page/intro/Intro.module.css
vs-code-home-page/styles/globals.css

Fix carousel and top blade styles.

Fix carousel and top blade styles

---

en/docs/implement-the-code/sequence-diagram-view.md
en/theme/material/base.html

Address more revamp review comments.

Address more revamp review comments

---

en/mkdocs.yml

Add the `Get Started` redirection.

Add the `Get Started` redirection

---

en/theme/material/base.html
en/theme/material/main.html

Fix the MD Banner element

---

en/theme/material/base.html

Update thumbnail image path in `base.html`.

Update thumbnail image path in `base.html`

---

en/theme/material/base.html

Update `base.html` for thumbnail image.

Update `base.html` for thumbnail image

---

en/mkdocs.yml

Update the path of the excluded VS Code folder.

Update the path of the excluded VS Code folder

---

en/mkdocs.yml

Remove home page

---

en/docs/build-executables.md
en/docs/configure-the-extension.md
en/docs/debug-the-code/debug-configurations.md
en/docs/debug-the-code/debug-features.md
en/docs/debug-the-code/debug-sessions.md
en/docs/debug-the-code/index.md
en/docs/design-the-application/design-using-the-architecture-view.md
en/docs/design-the-application/explore-the-architecture-view.md
en/docs/design-the-application/index.md
en/docs/design-the-services/graphql-api-designer.md
en/docs/design-the-services/http-api-designer.md
en/docs/implement-the-code/data-mapper.md
en/docs/implement-the-code/sequence-diagram-view.md
en/docs/index.md
en/docs/notebooks.md
en/docs/references/convert-json-to-records.md
en/docs/references/record-editor.md
en/docs/references/statement-editor/call-a-ballerina-library-function.md
en/docs/references/statement-editor/construct-a-record.md
en/docs/references/statement-editor/define-a-configurable-variable.md
en/docs/references/statement-editor/index.md
en/docs/run-a-program.md
en/docs/test-the-code.md
en/docs/try-the-services/try-graphql-services.md
en/docs/try-the-services/try-http-services.md
en/docs/write-the-code/code-actions.md
en/docs/write-the-code/code-navigation.md
en/docs/write-the-code/commands.md
en/docs/write-the-code/diagnostics.md
en/docs/write-the-code/intellisense.md

Review the VS Code docs

---

en/docs/release-notes/version-4.4.0.md

Add 4.4.0 documentation
